export const EMPLOYEE_DISPLAY_TYPES = {
    LIST: 'LIST',
    CARD: 'CARD', 
    DETAIL: 'DETAIL',
    DROPDOWN: 'DROPDOWN',
    AUTH: 'AUTH',
    MINIMAL: 'MINIMAL',
    SEARCH: 'SEARCH',
    REPORT: 'REPORT',
    PROJECT_ASSIGN: 'PROJECT_ASSIGN'
}